# Do not edit. Generated by the configure script.
BUILDTYPE=Release
NODE_TARGET_TYPE=shared_library
PYTHON=/usr/bin/python3.10
PREFIX=/home/kubasz/phd/wasmbounds/runner-build/default/nodejs
BUILD_WITH=ninja
